---
title: Statement of Purpose
author: Shuofan Zhang, Economics Department
bibliography: reference.bib
output:
  pdf_document:
    keep_tex: true
    latex_engine: xelatex
    template: default.tex
fontsize: 12pt
geometry: margin = 1in
header-includes:
    - \usepackage{setspace}\singlespacing
mainfont: Times New Roman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

It is my desire to pursue a PhD in Economics at University California, San Diego as part of my long-term professional goal of becoming an academic researcher. I have a strong interest in applied econometrics and macroeconomics.

<!--After graduating from college, I spent three years working for MSH China[^1] to meet my student loan obligations before beginning a Master's degree in Actuarial Studies at Monash University[^2]. My goal was to facilitate a future career as an actuary. However, I developed a keen interest in econometrics and academic research.--> This passion stemmed from the first econometric course of my master's program that was taught by Professor Farshid Vahid. I was fascinated by the idea of tackling real-world problems based on economic theories and statistical methods, thereby I cannot stop reading the textbook [@wooldridge2016]. It was then that I discovered three errors in the equations. Surprised by these errors, Professor Vahid wrote to Professor Jeffrey Wooldridge, which resulted in for me his appreciation, public praise in class, and extra course credit points. Encouraged by this experience, I decided to pursue my interest in econometrics and transferred my specialization from actuarial studies to applied econometrics. 

In the year that followed, I received the *Student Excellence Award* for achieving the highest mark in seven out of eight courses. In April 2018, I was chosen as one of the four representatives of Monash Business School to participate in the *Econometric Game*[^3], where the best PhD and master students from thirty prestigious universities including Harvard University and University of Cambridge study a same question and deliver academic papers for competition. This year's research topic was around the detrimental effects of an individual's unemployment on that individual's happiness as well as on a group's wellbeing. After reviewing the relevant literature for the empirical support on selecting explanatory variables, our team constructed an ordered probit model with the raw responses to the survey item that elicits respondents' overall life satisfaction as the dependent variable. Under the assumption of the homogeneous spillover effects amongst individuals in a group, we then estimated the multiplier between the effects on an individual and a group. The potential simultaneity bias was discussed. This great experience of conducting rigorous research provided me with important new insights into how unemployment affects well-being, and significantly stimulated my interest in empirical research in economics.

Measures of happiness, previously psychologists' tools, now are widely used by economists; likewise, statisticians' findings are infiltrating econometrics.  

<!--I first learned the values of statistical tools from another interesting competition for predicting housing prices in the statistical subject taught by Professor Dianne Cook when my random forest regression outperformed all the linear regressions. Studying more on the machine learning technique, I realized its similarity to econometrics and became curious about possible applications of this novel tool to economic studies.-->
As an attempt to introduce a statistical technique to econometrics, my master's thesis employed deep learning to facilitate the hypothesis test design, which was supervised by Professor Dianne Cook. Deriving hypothesis tests and the asymptotic distributions constitute a considerable part of the econometric literature.<!--detecting violations of the Gauss-Markov assumptions in multiple regression models is crucial for robust interpretations of the empirical results.--> However, the derivation is often complex and the resulting test may be powerless. For example, the Hausman tests and the unit root tests all suffer from low power.<!--@ANS73 has shown that single statistics may contain less information than data plots.  @MM13, where the hypothesis test based on human evaluations of visualized plots has been shown as valid,-->  In my thesis, I trained a binary deep learning classifier to detect linear relationships from no structure in a scatter plot as an alternative to the conventional $t$-test. Tested on a large unseen dataset, the power ($1-\beta$) of the classifier was always close to the $t$-test holding the type I error ($\alpha$) constant. Given that the $t$-test is the known uniformly most powerful test under such experimental settings [@Neyman289], this finding suggests the deep learning model has the potential to approach the unknown best test in more complicated situations. The study was then extended to test the null of homoscedasticity against heteroscedasticity using the retrained classifier. A small dataset of human evaluations was collected via an online questionnaire [@MM13] and a specific form of the White test [@white] was applied to provide a reference level of the test accuracy. The classifier achieved much higher accuracy than both the White test and humans. Using the data plot as the test statistic instead of a single quantity, this approach could avoid complex derivations while exploiting the useful information in the plots [@ANS73]. Although the training design could be challenging, these results empower future research. For instance, by replacing the scatter plot with time plots one can use this approach to test the unit root in time series. I am currently writing a first-author paper on these results to submit to the *Statistical Analysis and Data Mining*. This study was also presented by Professor Cook as the $50^{th}$ *Belz* Lecture for the *Statistical Society of Victoria*[^4].

<!--More specifically,  Having trained a satisfactory model using simulated data, I tested it against a large unseen test set and compared the accuracy with the conventional t-test. These results empower future research on this new methodology.--> 

After completing the master degree, I was excited to accept an offer from Professor Heather Anderson and Professor Farshid Vahid as a research assistant to work on a paper that studying the high-dimensional predictive regression with the LASSO[^5] [@koo]. In this project, I reviewed the literature to investigate the compatibility (or restricted eigenvalue) condition and its implication of choosing the tuning parameter $\lambda$ for the $\ell_1$ norm to achieve the prediction optimality, while taking into account the potential consequences of inconsistency for variable selection by the LASSO [@buhlmann]. I have been self studying Real Analysis by reading the book *Principles of Mathematical Analysis*[@rudin] to better understand the relevant concepts. Comparison between the LASSO, the adaptive LASSO and the group LASSO is under considering. In addition, the out-of-sample mean squared errors of forecasting GDP growth and inflation rate using the LASSO on 146 macroeconomics variables are compared against other approaches including an autoregressive model and a principal component analysis. The potential co-integrating relationships in the selected variables are being studied. Observing the series chosen by this data-driven methodology and seeking possible economic theory-based explanations are intriguing and encourage me to learn more. I want to continue to work on macroeconomic problems and apply cutting-edge techniques to challenging areas such as high-dimensional data and forecasting economic or financial series.

Meanwhile, I am co-authoring a paper with the Learning and Teaching team at Monash University that measuring student levels of perceptions of live-streaming, a new technology implemented in the lectures. Our study adapted the CRiSP[^6] questionnaire [@crisp] which was validated by a combination of factor analyses. Results revealed three reliable scales: acceptance, usability, and confidence. Following the validation results, I have investigated the correlations between student perceptions of live-streaming and their study attitudes using the estimated factor scores. The treatment effect of live-streaming on students academic performance is also being studied by the fixed effects model with panel data accounting for the unobserved heterogeneity.

Though I am open to a variety of research in Economics, I find the work of Professor Elliott, Timmermann, and Hamilton are especially interesting to me. I am confident that my talent in Mathematics combined with my various research experiences in Economics will allow me to contribute positively to the PhD program at University California, San Diego. 


<!-- Footnotes --> 
[^1]: MSH China is the Asia-Pacific Headquarter of MSH INTERNATIONA, a world leader in the design and management of international healthcare solutions. See <http://www.mshchina.com/>
[^2]: Monash University is a public research university based in Melbourne, Australia.
[^3]: The Econometric Game is hosted by the University of Amsterdam. See <http://econometricgame.nl/>
[^5]: LASSO is the abbreviation for Least Absolute Shrinkage and Selection Operator.
[^4]: The Victorian Branch of the Statistical Society of Australia Inc. See <https://www.statsoc.org.au/branches/victoria/>
[^6]: CRiSP is the name of classroom response system perceptions questionnaire.



# References





